version: "3.9"

services:
  # MySQL Database
  db-noorimmo:
    image: mysql:8.0
    container_name: noorimmo-db
    restart: always
    environment:
      MYSQL_DATABASE: noorimmo
      MYSQL_ROOT_PASSWORD: sUrjw1aA7j3gr7q7lidC
      MYSQL_PASSWORD: sUrjw1aA7j3gr7q7lidC
      MYSQL_USER: BinAbdallah
    ports:
      - "3306:3306"
    volumes:
      - db-noor-immo-data:/var/lib/mysql

  # PHP-FPM for Laravel
  api-noor-immo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noor-immo-api
    restart: always
    working_dir: /var/www
    depends_on:
      - db-noorimmo
    environment:
      DB_HOST: db-noorimmo
      DB_DATABASE: noorimmo
      DB_USERNAME: BinAbdallah
      DB_PASSWORD: sUrjw1aA7j3gr7q7lidC
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"

  # Nginx
  nginx-noorimmo:
    image: nginx:latest
    container_name: noorimmo-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api-noor-immo
    volumes:
      - ./public:/var/www/public
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./logs/nginx:/var/log/nginx

volumes:
  db-noor-immo-data:
